"""create455

Revision ID: ad084de444fe
Revises: 
Create Date: 2024-11-14 02:10:54.995912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad084de444fe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_directions")),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("foo", sa.Integer(), nullable=False),
        sa.Column("bar", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("foo", "bar", name=op.f("uq_users_foo_bar")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "hotels",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("advantage", sa.String(), nullable=False),
        sa.Column("url_img", sa.String(), nullable=False),
        sa.Column("id_direction", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_direction"],
            ["directions.id"],
            name=op.f("fk_hotels_id_direction_directions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hotels")),
        sa.UniqueConstraint("name", name=op.f("uq_hotels_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hotels")
    op.drop_table("users")
    op.drop_table("directions")
    # ### end Alembic commands ###
